kind = "api"
previewPath = "/api"
title = "Razoreye API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Razoreye"
paths = ["/api"]

[services.development]
run = "uv run gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 razoreye:app"

[services.production]

[services.production.build]
args = ["sh", "-c", "true"]

[services.production.run]
args = ["uv", "run", "gunicorn", "--chdir", "artifacts/api-server", "--bind", "0.0.0.0:8080", "--workers", "1", "--threads", "4", "razoreye:app"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/healthz"
